name: Створення архіву релізу

on:
  release:
    types: [published] # Скрипт спрацює в момент натискання кнопки "Publish release"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Завантажуємо код репозиторію
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Створюємо чистий ZIP-архів (без папки .git)
      - name: Create ZIP Archive
        run: |
          zip -r WeatherInUkraine.zip . -x "*.git*" "*demo.mp4*"

      # 3. Автоматично завантажуємо його в Assets створеного релізу
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: WeatherInUkraine.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
