name: Створення архіву релізу

on:
  release:
    types: [published]

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Завантажуємо код проєкту
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Пакуємо чистий архів без системного сміття та важких відео
      - name: Create ZIP archive
        run: |
          zip -r WeatherInUkraine.zip . -x "*.git*" "*demo.mp4*"

      # 3. Вбудована офіційна команда GitHub для прикріплення файлу до релізу
      - name: Upload asset to release
        run: gh release upload ${{ github.event.release.tag_name }} WeatherInUkraine.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
